# sample data for created tables

import psycopg2
from config import DB_CONFIG

def insert_values_into_tables():
    commands = ["""
        insert into artists (name, country) values 
        ('Metallica', 'USA'),
        ('Slayer', 'USA'),
        ('Pantera', 'USA'),
        ('Slipknot', 'USA'),
        ('Lamb of God', 'USA'),
        ('Gojira', 'France'),
        ('In Flames', 'Sweden'),
        ('Children of Bodom', 'Finland'),
        ('Nightwish', 'Finland'),
        ('System of a Down', 'USA'),
        ('Arch Enemy', 'Sweden'),
        ('Behemoth', 'Poland'),
        ('Sepultura', 'Brazil'),
        ('Zeal&Ardor', 'Switzerland');
        """,
        """
    INSERT INTO albums (name, release_year, artist_id) VALUES
    ('Master of Puppets', 1986, (SELECT id FROM artists WHERE name = 'Metallica')),
    ('Ride the Lightning', 1984, (SELECT id FROM artists WHERE name = 'Metallica')),
    ('...And Justice for All', 1988, (SELECT id FROM artists WHERE name = 'Metallica')),
    ('Reign in Blood', 1986, (SELECT id FROM artists WHERE name = 'Slayer')),
    ('Seasons in the Abyss', 1990, (SELECT id FROM artists WHERE name = 'Slayer')),
    ('South of Heaven', 1988, (SELECT id FROM artists WHERE name = 'Slayer')),
    ('Cowboys from Hell', 1990, (SELECT id FROM artists WHERE name = 'Pantera')),
    ('Vulgar Display of Power', 1992, (SELECT id FROM artists WHERE name = 'Pantera')),
    ('Far Beyond Driven', 1994, (SELECT id FROM artists WHERE name = 'Pantera')),
    ('Slipknot', 1999, (SELECT id FROM artists WHERE name = 'Slipknot')),
    ('Iowa', 2001, (SELECT id FROM artists WHERE name = 'Slipknot')),
    ('Vol. 3: The Subliminal Verses', 2004, (SELECT id FROM artists WHERE name = 'Slipknot')),
    ('Ashes of the Wake', 2004, (SELECT id FROM artists WHERE name = 'Lamb of God')),
    ('Sacrament', 2006, (SELECT id FROM artists WHERE name = 'Lamb of God')),
    ('Wrath', 2009, (SELECT id FROM artists WHERE name = 'Lamb of God')),
    ('L''Enfant Sauvage', 2012, (SELECT id FROM artists WHERE name = 'Gojira')),
    ('Magma', 2016, (SELECT id FROM artists WHERE name = 'Gojira')),
    ('Fortitude', 2021, (SELECT id FROM artists WHERE name = 'Gojira')),
    ('Clayman', 2000, (SELECT id FROM artists WHERE name = 'In Flames')),
    ('Come Clarity', 2006, (SELECT id FROM artists WHERE name = 'In Flames')),
    ('I, the Mask', 2019, (SELECT id FROM artists WHERE name = 'In Flames')),
    ('Hatebreeder', 1999, (SELECT id FROM artists WHERE name = 'Children of Bodom')),
    ('Follow the Reaper', 2000, (SELECT id FROM artists WHERE name = 'Children of Bodom')),
    ('Halo of Blood', 2013, (SELECT id FROM artists WHERE name = 'Children of Bodom')),
    ('Oceanborn', 1998, (SELECT id FROM artists WHERE name = 'Nightwish')),
    ('Once', 2004, (SELECT id FROM artists WHERE name = 'Nightwish')),
    ('Endless Forms Most Beautiful', 2015, (SELECT id FROM artists WHERE name = 'Nightwish')),
    ('Toxicity', 2001, (SELECT id FROM artists WHERE name = 'System of a Down')),
    ('Mezmerize', 2005, (SELECT id FROM artists WHERE name = 'System of a Down')),
    ('Hypnotize', 2005, (SELECT id FROM artists WHERE name = 'System of a Down')),
    ('Wages of Sin', 2001, (SELECT id FROM artists WHERE name = 'Arch Enemy')),
    ('Doomsday Machine', 2005, (SELECT id FROM artists WHERE name = 'Arch Enemy')),
    ('Deceivers', 2022, (SELECT id FROM artists WHERE name = 'Arch Enemy')),
    ('Demigod', 2004, (SELECT id FROM artists WHERE name = 'Behemoth')),
    ('The Satanist', 2014, (SELECT id FROM artists WHERE name = 'Behemoth')),
    ('Opvs Contra Natvram', 2022, (SELECT id FROM artists WHERE name = 'Behemoth')),
    ('Chaos A.D.', 1993, (SELECT id FROM artists WHERE name = 'Sepultura')),
    ('Roots', 1996, (SELECT id FROM artists WHERE name = 'Sepultura')),
    ('Machine Messiah', 2017, (SELECT id FROM artists WHERE name = 'Sepultura')),
    ('Stranger Fruit', 2018, (SELECT id FROM artists WHERE name = 'Zeal&Ardor')),
    ('Wake of a Nation', 2020, (SELECT id FROM artists WHERE name = 'Zeal&Ardor')),
    ('Zeal & Ardor', 2022, (SELECT id FROM artists WHERE name = 'Zeal&Ardor'));
    """,
        """
        INSERT INTO songs (title, duration, album_id, artist_id) VALUES
    ('Battery', '00:03:12', (SELECT id FROM albums WHERE name = 'Master of Puppets'), (SELECT id FROM artists WHERE name = 'Metallica')),
    ('Master of Puppets', '00:05:15', (SELECT id FROM albums WHERE name = 'Master of Puppets'), (SELECT id FROM artists WHERE name = 'Metallica')),
    ('Welcome Home (Sanitarium)', '00:04:31', (SELECT id FROM albums WHERE name = 'Master of Puppets'), (SELECT id FROM artists WHERE name = 'Metallica')),
    ('Disposable Heroes', '00:04:36', (SELECT id FROM albums WHERE name = 'Master of Puppets'), (SELECT id FROM artists WHERE name = 'Metallica')),
    ('Orion', '00:04:38', (SELECT id FROM albums WHERE name = 'Master of Puppets'), (SELECT id FROM artists WHERE name = 'Metallica')),
    ('Fight Fire with Fire', '00:02:24', (SELECT id FROM albums WHERE name = 'Ride the Lightning'), (SELECT id FROM artists WHERE name = 'Metallica')),
    ('Ride the Lightning', '00:03:37', (SELECT id FROM albums WHERE name = 'Ride the Lightning'), (SELECT id FROM artists WHERE name = 'Metallica')),
    ('Fade to Black', '00:06:58', (SELECT id FROM albums WHERE name = 'Ride the Lightning'), (SELECT id FROM artists WHERE name = 'Metallica')),
    ('Creeping Death', '00:06:36', (SELECT id FROM albums WHERE name = 'Ride the Lightning'), (SELECT id FROM artists WHERE name = 'Metallica')),
    ('The Call of Ktulu', '00:08:53', (SELECT id FROM albums WHERE name = 'Ride the Lightning'), (SELECT id FROM artists WHERE name = 'Metallica')),
    ('Blackened', '00:06:17', (SELECT id FROM albums WHERE name = '...And Justice for All'), (SELECT id FROM artists WHERE name = 'Metallica')),
    ('...And Justice for All', '00:09:48', (SELECT id FROM albums WHERE name = '...And Justice for All'), (SELECT id FROM artists WHERE name = 'Metallica')),
    ('One', '00:07:27', (SELECT id FROM albums WHERE name = '...And Justice for All'), (SELECT id FROM artists WHERE name = 'Metallica')),
    ('Harvester of Sorrow', '00:05:30', (SELECT id FROM albums WHERE name = '...And Justice for All'), (SELECT id FROM artists WHERE name = 'Metallica')),
    ('Dyers Eve', '00:05:16', (SELECT id FROM albums WHERE name = '...And Justice for All'), (SELECT id FROM artists WHERE name = 'Metallica')),
    ('Angel of Death', '00:04:46', (SELECT id FROM albums WHERE name = 'Reign in Blood'), (SELECT id FROM artists WHERE name = 'Slayer')),
    ('Piece by Piece', '00:02:22', (SELECT id FROM albums WHERE name = 'Reign in Blood'), (SELECT id FROM artists WHERE name = 'Slayer')),
    ('Necrophobic', '00:01:40', (SELECT id FROM albums WHERE name = 'Reign in Blood'), (SELECT id FROM artists WHERE name = 'Slayer')),
    ('Altar of Sacrifice', '00:02:53', (SELECT id FROM albums WHERE name = 'Reign in Blood'), (SELECT id FROM artists WHERE name = 'Slayer')),
    ('Jesus Saves', '00:02:51', (SELECT id FROM albums WHERE name = 'Reign in Blood'), (SELECT id FROM artists WHERE name = 'Slayer')),
    ('War Ensemble', '00:04:58', (SELECT id FROM albums WHERE name = 'Seasons in the Abyss'), (SELECT id FROM artists WHERE name = 'Slayer')),
    ('Blood Red', '00:04:04', (SELECT id FROM albums WHERE name = 'Seasons in the Abyss'), (SELECT id FROM artists WHERE name = 'Slayer')),
    ('Spirit in Black', '00:04:26', (SELECT id FROM albums WHERE name = 'Seasons in the Abyss'), (SELECT id FROM artists WHERE name = 'Slayer')),
    ('Expendable Youth', '00:04:11', (SELECT id FROM albums WHERE name = 'Seasons in the Abyss'), (SELECT id FROM artists WHERE name = 'Slayer')),
    ('Dead Skin Mask', '00:05:11', (SELECT id FROM albums WHERE name = 'Seasons in the Abyss'), (SELECT id FROM artists WHERE name = 'Slayer')),
    ('South of Heaven', '00:04:54', (SELECT id FROM albums WHERE name = 'South of Heaven'), (SELECT id FROM artists WHERE name = 'Slayer')),
    ('Silent Scream', '00:03:48', (SELECT id FROM albums WHERE name = 'South of Heaven'), (SELECT id FROM artists WHERE name = 'Slayer')),
    ('Live Undead', '00:03:36', (SELECT id FROM albums WHERE name = 'South of Heaven'), (SELECT id FROM artists WHERE name = 'Slayer')),
    ('Behind the Crooked Cross', '00:04:18', (SELECT id FROM albums WHERE name = 'South of Heaven'), (SELECT id FROM artists WHERE name = 'Slayer')),
    ('Mandatory Suicide', '00:04:41', (SELECT id FROM albums WHERE name = 'South of Heaven'), (SELECT id FROM artists WHERE name = 'Slayer')),
    ('Cowboys from Hell', '00:04:24', (SELECT id FROM albums WHERE name = 'Cowboys from Hell'), (SELECT id FROM artists WHERE name = 'Pantera')),
    ('Cemetery Gates', '00:07:15', (SELECT id FROM albums WHERE name = 'Cowboys from Hell'), (SELECT id FROM artists WHERE name = 'Pantera')),
    ('Domination', '00:05:32', (SELECT id FROM albums WHERE name = 'Cowboys from Hell'), (SELECT id FROM artists WHERE name = 'Pantera')),
    ('Psycho Holiday', '00:05:19', (SELECT id FROM albums WHERE name = 'Cowboys from Hell'), (SELECT id FROM artists WHERE name = 'Pantera')),
    ('Shattered', '00:03:42', (SELECT id FROM albums WHERE name = 'Cowboys from Hell'), (SELECT id FROM artists WHERE name = 'Pantera')),
    ('Mouth for War', '00:03:48', (SELECT id FROM albums WHERE name = 'Vulgar Display of Power'), (SELECT id FROM artists WHERE name = 'Pantera')),
    ('Walk', '00:05:10', (SELECT id FROM albums WHERE name = 'Vulgar Display of Power'), (SELECT id FROM artists WHERE name = 'Pantera')),
    ('This Love', '00:06:20', (SELECT id FROM albums WHERE name = 'Vulgar Display of Power'), (SELECT id FROM artists WHERE name = 'Pantera')),
    ('Rise', '00:04:21', (SELECT id FROM albums WHERE name = 'Vulgar Display of Power'), (SELECT id FROM artists WHERE name = 'Pantera')),
    ('Regular People (Conceit)', '00:05:15', (SELECT id FROM albums WHERE name = 'Vulgar Display of Power'), (SELECT id FROM artists WHERE name = 'Pantera')),
    ('Strength Beyond Strength', '00:03:15', (SELECT id FROM albums WHERE name = 'Far Beyond Driven'), (SELECT id FROM artists WHERE name = 'Pantera')),
    ('Becoming', '00:03:30', (SELECT id FROM albums WHERE name = 'Far Beyond Driven'), (SELECT id FROM artists WHERE name = 'Pantera')),
    ('5 Minutes Alone', '00:05:16', (SELECT id FROM albums WHERE name = 'Far Beyond Driven'), (SELECT id FROM artists WHERE name = 'Pantera')),
    ('I’m Broken', '00:04:31', (SELECT id FROM albums WHERE name = 'Far Beyond Driven'), (SELECT id FROM artists WHERE name = 'Pantera')),
    ('Slaughtered', '00:03:43', (SELECT id FROM albums WHERE name = 'Far Beyond Driven'), (SELECT id FROM artists WHERE name = 'Pantera')),
    ('(sic)', '00:03:34', (SELECT id FROM albums WHERE name = 'Slipknot'), (SELECT id FROM artists WHERE name = 'Slipknot')),
    ('Eyeless', '00:03:50', (SELECT id FROM albums WHERE name = 'Slipknot'), (SELECT id FROM artists WHERE name = 'Slipknot')),
    ('Wait and Bleed', '00:02:55', (SELECT id FROM albums WHERE name = 'Slipknot'), (SELECT id FROM artists WHERE name = 'Slipknot')),
    ('Spit It Out', '00:02:58', (SELECT id FROM albums WHERE name = 'Slipknot'), (SELECT id FROM artists WHERE name = 'Slipknot')),
    ('Surfacing', '00:03:56', (SELECT id FROM albums WHERE name = 'Slipknot'), (SELECT id FROM artists WHERE name = 'Slipknot')),
    ('People = Shit', '00:03:35', (SELECT id FROM albums WHERE name = 'Iowa'), (SELECT id FROM artists WHERE name = 'Slipknot')),
    ('Disasterpiece', '00:05:02', (SELECT id FROM albums WHERE name = 'Iowa'), (SELECT id FROM artists WHERE name = 'Slipknot')),
    ('My Plague', '00:03:38', (SELECT id FROM albums WHERE name = 'Iowa'), (SELECT id FROM artists WHERE name = 'Slipknot')),
    ('The Heretic Anthem', '00:04:10', (SELECT id FROM albums WHERE name = 'Iowa'), (SELECT id FROM artists WHERE name = 'Slipknot')),
    ('Left Behind', '00:04:08', (SELECT id FROM albums WHERE name = 'Iowa'), (SELECT id FROM artists WHERE name = 'Slipknot')),
    ('Duality', '00:04:04', (SELECT id FROM albums WHERE name = 'Vol. 3: The Subliminal Verses'), (SELECT id FROM artists WHERE name = 'Slipknot')),
    ('Before I Forget', '00:04:21', (SELECT id FROM albums WHERE name = 'Vol. 3: The Subliminal Verses'), (SELECT id FROM artists WHERE name = 'Slipknot')),
    ('Vermilion', '00:05:19', (SELECT id FROM albums WHERE name = 'Vol. 3: The Subliminal Verses'), (SELECT id FROM artists WHERE name = 'Slipknot')),
    ('Pulse of the Maggots', '00:04:57', (SELECT id FROM albums WHERE name = 'Vol. 3: The Subliminal Verses'), (SELECT id FROM artists WHERE name = 'Slipknot')),
    ('The Nameless', '00:04:52', (SELECT id FROM albums WHERE name = 'Vol. 3: The Subliminal Verses'), (SELECT id FROM artists WHERE name = 'Slipknot')),
    ('Laid to Rest', '00:03:58', (SELECT id FROM albums WHERE name = 'Ashes of the Wake'), (SELECT id FROM artists WHERE name = 'Lamb of God')),
    ('Hourglass', '00:04:17', (SELECT id FROM albums WHERE name = 'Ashes of the Wake'), (SELECT id FROM artists WHERE name = 'Lamb of God')),
    ('Now You’ve Got Something to Die For', '00:03:52', (SELECT id FROM albums WHERE name = 'Ashes of the Wake'), (SELECT id FROM artists WHERE name = 'Lamb of God')),
    ('Omerta', '00:04:48', (SELECT id FROM albums WHERE name = 'Ashes of the Wake'), (SELECT id FROM artists WHERE name = 'Lamb of God')),
    ('Blood of the Scribe', '00:05:15', (SELECT id FROM albums WHERE name = 'Ashes of the Wake'), (SELECT id FROM artists WHERE name = 'Lamb of God')),
    ('Walk with Me in Hell', '00:05:42', (SELECT id FROM albums WHERE name = 'Sacrament'), (SELECT id FROM artists WHERE name = 'Lamb of God')),
    ('Again We Rise', '00:04:04', (SELECT id FROM albums WHERE name = 'Sacrament'), (SELECT id FROM artists WHERE name = 'Lamb of God')),
    ('Redneck', '00:03:46', (SELECT id FROM albums WHERE name = 'Sacrament'), (SELECT id FROM artists WHERE name = 'Lamb of God')),
    ('Pathetic', '00:04:35', (SELECT id FROM albums WHERE name = 'Sacrament'), (SELECT id FROM artists WHERE name = 'Lamb of God')),
    ('Blacken the Cursed Sun', '00:05:15', (SELECT id FROM albums WHERE name = 'Sacrament'), (SELECT id FROM artists WHERE name = 'Lamb of God')),
    ('In Your Words', '00:05:38', (SELECT id FROM albums WHERE name = 'Wrath'), (SELECT id FROM artists WHERE name = 'Lamb of God')),
    ('Set to Fail', '00:04:04', (SELECT id FROM albums WHERE name = 'Wrath'), (SELECT id FROM artists WHERE name = 'Lamb of God')),
    ('Contractor', '00:03:33', (SELECT id FROM albums WHERE name = 'Wrath'), (SELECT id FROM artists WHERE name = 'Lamb of God')),
    ('Fake Messiah', '00:04:46', (SELECT id FROM albums WHERE name = 'Wrath'), (SELECT id FROM artists WHERE name = 'Lamb of God')),
    ('Broken Hands', '00:04:53', (SELECT id FROM albums WHERE name = 'Wrath'), (SELECT id FROM artists WHERE name = 'Lamb of God')),
    ('Explosia', '00:06:09', (SELECT id FROM albums WHERE name = 'L''Enfant Sauvage'), (SELECT id FROM artists WHERE name = 'Gojira')),
    ('L''Enfant Sauvage', '00:04:15', (SELECT id FROM albums WHERE name = 'L''Enfant Sauvage'), (SELECT id FROM artists WHERE name = 'Gojira')),
    ('The Axe', '00:04:27', (SELECT id FROM albums WHERE name = 'L''Enfant Sauvage'), (SELECT id FROM artists WHERE name = 'Gojira')),
    ('The Gift of Guilt', '00:05:42', (SELECT id FROM albums WHERE name = 'L''Enfant Sauvage'), (SELECT id FROM artists WHERE name = 'Gojira')),
    ('Pain Is a Master', '00:04:58', (SELECT id FROM albums WHERE name = 'L''Enfant Sauvage'), (SELECT id FROM artists WHERE name = 'Gojira')),
    ('Silvera', '00:03:36', (SELECT id FROM albums WHERE name = 'Magma'), (SELECT id FROM artists WHERE name = 'Gojira')),
    ('Stranded', '00:04:00', (SELECT id FROM albums WHERE name = 'Magma'), (SELECT id FROM artists WHERE name = 'Gojira')),
    ('The Shooting Star', '00:05:05', (SELECT id FROM albums WHERE name = 'Magma'), (SELECT id FROM artists WHERE name = 'Gojira')),
    ('Pray', '00:05:19', (SELECT id FROM albums WHERE name = 'Magma'), (SELECT id FROM artists WHERE name = 'Gojira')),
    ('Only Pain', '00:04:57', (SELECT id FROM albums WHERE name = 'Magma'), (SELECT id FROM artists WHERE name = 'Gojira')),
    ('Born for One Thing', '00:04:16', (SELECT id FROM albums WHERE name = 'Fortitude'), (SELECT id FROM artists WHERE name = 'Gojira')),
    ('Amazonia', '00:04:41', (SELECT id FROM albums WHERE name = 'Fortitude'), (SELECT id FROM artists WHERE name = 'Gojira')),
    ('Another World', '00:04:34', (SELECT id FROM albums WHERE name = 'Fortitude'), (SELECT id FROM artists WHERE name = 'Gojira')),
    ('Hold On', '00:05:12', (SELECT id FROM albums WHERE name = 'Fortitude'), (SELECT id FROM artists WHERE name = 'Gojira')),
    ('The Chant', '00:05:30', (SELECT id FROM albums WHERE name = 'Fortitude'), (SELECT id FROM artists WHERE name = 'Gojira')),
    ('Bullet Ride', '00:04:37', (SELECT id FROM albums WHERE name = 'Clayman'), (SELECT id FROM artists WHERE name = 'In Flames')),
    ('Pinball Map', '00:04:21', (SELECT id FROM albums WHERE name = 'Clayman'), (SELECT id FROM artists WHERE name = 'In Flames')),
    ('Only for the Weak', '00:04:54', (SELECT id FROM albums WHERE name = 'Clayman'), (SELECT id FROM artists WHERE name = 'In Flames')),
    ('Clayman', '00:03:59', (SELECT id FROM albums WHERE name = 'Clayman'), (SELECT id FROM artists WHERE name = 'In Flames')),
    ('Suburban Me', '00:04:55', (SELECT id FROM albums WHERE name = 'Clayman'), (SELECT id FROM artists WHERE name = 'In Flames')),
    ('Take This Life', '00:03:49', (SELECT id FROM albums WHERE name = 'Come Clarity'), (SELECT id FROM artists WHERE name = 'In Flames')),
    ('Leeches', '00:03:24', (SELECT id FROM albums WHERE name = 'Come Clarity'), (SELECT id FROM artists WHERE name = 'In Flames')),
    ('Reflect the Storm', '00:04:34', (SELECT id FROM albums WHERE name = 'Come Clarity'), (SELECT id FROM artists WHERE name = 'In Flames')),
    ('Dead End', '00:04:01', (SELECT id FROM albums WHERE name = 'Come Clarity'), (SELECT id FROM artists WHERE name = 'In Flames')),
    ('Come Clarity', '00:04:28', (SELECT id FROM albums WHERE name = 'Come Clarity'), (SELECT id FROM artists WHERE name = 'In Flames')),
    ('Voices', '00:04:27', (SELECT id FROM albums WHERE name = 'I, the Mask'), (SELECT id FROM artists WHERE name = 'In Flames')),
    ('I, the Mask', '00:03:48', (SELECT id FROM albums WHERE name = 'I, the Mask'), (SELECT id FROM artists WHERE name = 'In Flames')),
    ('Call My Name', '00:04:25', (SELECT id FROM albums WHERE name = 'I, the Mask'), (SELECT id FROM artists WHERE name = 'In Flames')),
    ('Burn', '00:04:01', (SELECT id FROM albums WHERE name = 'I, the Mask'), (SELECT id FROM artists WHERE name = 'In Flames')),
    ('Deep Inside', '00:04:58', (SELECT id FROM albums WHERE name = 'I, the Mask'), (SELECT id FROM artists WHERE name = 'In Flames')),
    ('Warheart', '00:03:58', (SELECT id FROM albums WHERE name = 'Hatebreeder'), (SELECT id FROM artists WHERE name = 'Children of Bodom')),
    ('Silent Night, Bodom Night', '00:04:05', (SELECT id FROM albums WHERE name = 'Hatebreeder'), (SELECT id FROM artists WHERE name = 'Children of Bodom')),
    ('Hatebreeder', '00:04:18', (SELECT id FROM albums WHERE name = 'Hatebreeder'), (SELECT id FROM artists WHERE name = 'Children of Bodom')),
    ('Bed of Razors', '00:04:43', (SELECT id FROM albums WHERE name = 'Hatebreeder'), (SELECT id FROM artists WHERE name = 'Children of Bodom')),
    ('Children of Decadence', '00:05:11', (SELECT id FROM albums WHERE name = 'Hatebreeder'), (SELECT id FROM artists WHERE name = 'Children of Bodom')),
    ('Everytime I Die', '00:05:06', (SELECT id FROM albums WHERE name = 'Follow the Reaper'), (SELECT id FROM artists WHERE name = 'Children of Bodom')),
    ('Bodom After Midnight', '00:04:48', (SELECT id FROM albums WHERE name = 'Follow the Reaper'), (SELECT id FROM artists WHERE name = 'Children of Bodom')),
    ('Mask of Sanity', '00:04:54', (SELECT id FROM albums WHERE name = 'Follow the Reaper'), (SELECT id FROM artists WHERE name = 'Children of Bodom')),
    ('Taste of My Scythe', '00:04:25', (SELECT id FROM albums WHERE name = 'Follow the Reaper'), (SELECT id FROM artists WHERE name = 'Children of Bodom')),
    ('Kissing the Shadows', '00:05:42', (SELECT id FROM albums WHERE name = 'Follow the Reaper'), (SELECT id FROM artists WHERE name = 'Children of Bodom')),
    ('Stargazers', '00:04:28', (SELECT id FROM albums WHERE name = 'Oceanborn'), (SELECT id FROM artists WHERE name = 'Nightwish')),
    ('Gethsemane', '00:05:01', (SELECT id FROM albums WHERE name = 'Oceanborn'), (SELECT id FROM artists WHERE name = 'Nightwish')),
    ('Sacrament of Wilderness', '00:04:40', (SELECT id FROM albums WHERE name = 'Oceanborn'), (SELECT id FROM artists WHERE name = 'Nightwish')),
    ('Sleeping Sun', '00:04:26', (SELECT id FROM albums WHERE name = 'Oceanborn'), (SELECT id FROM artists WHERE name = 'Nightwish')),
    ('Passion and the Opera', '00:04:50', (SELECT id FROM albums WHERE name = 'Oceanborn'), (SELECT id FROM artists WHERE name = 'Nightwish')),
    ('Dark Chest of Wonders', '00:04:28', (SELECT id FROM albums WHERE name = 'Once'), (SELECT id FROM artists WHERE name = 'Nightwish')),
    ('Wish I Had an Angel', '00:04:25', (SELECT id FROM albums WHERE name = 'Once'), (SELECT id FROM artists WHERE name = 'Nightwish')),
    ('Nemo', '00:04:38', (SELECT id FROM albums WHERE name = 'Once'), (SELECT id FROM artists WHERE name = 'Nightwish')),
    ('Planet Hell', '00:04:37', (SELECT id FROM albums WHERE name = 'Once'), (SELECT id FROM artists WHERE name = 'Nightwish')),
    ('Higher Than Hope', '00:05:42', (SELECT id FROM albums WHERE name = 'Once'), (SELECT id FROM artists WHERE name = 'Nightwish')),
    ('Shudder Before the Beautiful', '00:05:36', (SELECT id FROM albums WHERE name = 'Endless Forms Most Beautiful'), (SELECT id FROM artists WHERE name = 'Nightwish')),
    ('Weak Fantasy', '00:05:24', (SELECT id FROM albums WHERE name = 'Endless Forms Most Beautiful'), (SELECT id FROM artists WHERE name = 'Nightwish')),
    ('Élan', '00:04:22', (SELECT id FROM albums WHERE name = 'Endless Forms Most Beautiful'), (SELECT id FROM artists WHERE name = 'Nightwish')),
    ('Alpenglow', '00:04:50', (SELECT id FROM albums WHERE name = 'Endless Forms Most Beautiful'), (SELECT id FROM artists WHERE name = 'Nightwish')),
    ('The Greatest Show on Earth', '00:23:54', (SELECT id FROM albums WHERE name = 'Endless Forms Most Beautiful'), (SELECT id FROM artists WHERE name = 'Nightwish')),
    ('Prison Song', '00:03:21', (SELECT id FROM albums WHERE name = 'Toxicity'), (SELECT id FROM artists WHERE name = 'System of a Down')),
    ('Needles', '00:03:27', (SELECT id FROM albums WHERE name = 'Toxicity'), (SELECT id FROM artists WHERE name = 'System of a Down')),
    ('Deer Dance', '00:02:50', (SELECT id FROM albums WHERE name = 'Toxicity'), (SELECT id FROM artists WHERE name = 'System of a Down')),
    ('Chop Suey!', '00:03:30', (SELECT id FROM albums WHERE name = 'Toxicity'), (SELECT id FROM artists WHERE name = 'System of a Down')),
    ('Toxicity', '00:03:39', (SELECT id FROM albums WHERE name = 'Toxicity'), (SELECT id FROM artists WHERE name = 'System of a Down')),
    ('Enemy Within', '00:05:28', (SELECT id FROM albums WHERE name = 'Wages of Sin'), (SELECT id FROM artists WHERE name = 'Arch Enemy')),
    ('Burning Angel', '00:04:32', (SELECT id FROM albums WHERE name = 'Wages of Sin'), (SELECT id FROM artists WHERE name = 'Arch Enemy')),
    ('Ravenous', '00:04:48', (SELECT id FROM albums WHERE name = 'Wages of Sin'), (SELECT id FROM artists WHERE name = 'Arch Enemy')),
    ('Savage Messiah', '00:04:53', (SELECT id FROM albums WHERE name = 'Wages of Sin'), (SELECT id FROM artists WHERE name = 'Arch Enemy')),
    ('Dead Bury Their Dead', '00:04:38', (SELECT id FROM albums WHERE name = 'Wages of Sin'), (SELECT id FROM artists WHERE name = 'Arch Enemy')),
    ('Slaves Shall Serve', '00:04:00', (SELECT id FROM albums WHERE name = 'Demigod'), (SELECT id FROM artists WHERE name = 'Behemoth')),
    ('Demigod', '00:04:19', (SELECT id FROM albums WHERE name = 'Demigod'), (SELECT id FROM artists WHERE name = 'Behemoth')),
    ('The Reign ov Shemsu-Hor', '00:05:57', (SELECT id FROM albums WHERE name = 'Demigod'), (SELECT id FROM artists WHERE name = 'Behemoth')),
    ('Before the Æons Came', '00:04:03', (SELECT id FROM albums WHERE name = 'Demigod'), (SELECT id FROM artists WHERE name = 'Behemoth')),
    ('Conquer All', '00:03:27', (SELECT id FROM albums WHERE name = 'Demigod'), (SELECT id FROM artists WHERE name = 'Behemoth')),
    ('Refuse/Resist', '00:03:19', (SELECT id FROM albums WHERE name = 'Chaos A.D.'), (SELECT id FROM artists WHERE name = 'Sepultura')),
    ('Territory', '00:04:47', (SELECT id FROM albums WHERE name = 'Chaos A.D.'), (SELECT id FROM artists WHERE name = 'Sepultura')),
    ('Slave New World', '00:02:56', (SELECT id FROM albums WHERE name = 'Chaos A.D.'), (SELECT id FROM artists WHERE name = 'Sepultura')),
    ('Amen', '00:04:52', (SELECT id FROM albums WHERE name = 'Chaos A.D.'), (SELECT id FROM artists WHERE name = 'Sepultura')),
    ('Propaganda', '00:03:37', (SELECT id FROM albums WHERE name = 'Chaos A.D.'), (SELECT id FROM artists WHERE name = 'Sepultura')),
    ('Gravedigger’s Chant', '00:03:15', (SELECT id FROM albums WHERE name = 'Stranger Fruit'), (SELECT id FROM artists WHERE name = 'Zeal&Ardor')),
    ('Servants', '00:03:16', (SELECT id FROM albums WHERE name = 'Stranger Fruit'), (SELECT id FROM artists WHERE name = 'Zeal&Ardor')),
    ('Don’t You Dare', '00:03:43', (SELECT id FROM albums WHERE name = 'Stranger Fruit'), (SELECT id FROM artists WHERE name = 'Zeal&Ardor')),
    ('Fire of Motion', '00:01:42', (SELECT id FROM albums WHERE name = 'Stranger Fruit'), (SELECT id FROM artists WHERE name = 'Zeal&Ardor')),
    ('Waste', '00:02:38', (SELECT id FROM albums WHERE name = 'Stranger Fruit'), (SELECT id FROM artists WHERE name = 'Zeal&Ardor'));
"""
            ]
    try:
        with psycopg2.connect(**DB_CONFIG) as connect_db:
            with connect_db.cursor() as cursor:
                for command in commands:
                    cursor.execute(command)
            connect_db.commit()
    except Exception as ex:
        print(f"Error with creation {ex}")

if __name__ == "__main__":
    insert_values_into_tables()



