"""Constraint by title,artist,album added to songs

Revision ID: 99a1859fb135
Revises: 79965829293a
Create Date: 2025-02-20 19:38:49.312196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a1859fb135'
down_revision: Union[str, None] = '79965829293a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_album_artist_song_name', 'songs', ['title', 'album_id', 'artist_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_album_artist_song_name', 'songs', type_='unique')
    # ### end Alembic commands ###
