# Generated by Django 5.1.7 on 2025-03-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_bookitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='genre',
            field=models.CharField(blank=True, choices=[('Fantasy', 'Fantasy'), ('Science', 'Science'), ('Fiction', 'Fiction'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Dystopian', 'Dystopian'), ('Magical', 'Magical'), ('Realism', 'Realism'), ('Adventure', 'Adventure'), ('Biography&Autobiography', 'Biography&Autobiography'), ('Memoir', 'Memoir'), ('Self-Help', 'Self-Help'), ('History', 'History'), ('Philosophy', 'Philosophy'), ('Psychology', 'Psychology'), ('Business&Economics', 'Business&Economics'), ('TrueCrime', 'Truecrime'), ('Travel', 'Travel'), ('Cooking&Food', 'Cooking&Food'), ('Health&Wellness', 'Health&Wellness')], max_length=30, null=True),
        ),
    ]
