# Generated by Django 5.1.7 on 2025-03-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_bookitem_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookItem',
        ),
    ]
