# Generated by Django 5.1.7 on 2025-03-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('author', models.TextField()),
                ('genre', models.CharField(blank=True, choices=[('Fantasy', 'Fantasy'), ('Science', 'Science'), ('Fiction', 'Fiction'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Dystopian', 'Dystopian'), ('Magical', 'Magical'), ('Realism', 'Realism'), ('Adventure', 'Adventure'), ('Biography&Autobiography', 'Biography&Autobiography'), ('Memoir', 'Memoir'), ('Self-Help', 'Self-Help'), ('History', 'History'), ('Philosophy', 'Philosophy'), ('Psychology', 'Psychology'), ('Business&Economics', 'Business&Economics'), ('TrueCrime', 'Truecrime'), ('Travel', 'Travel'), ('Cooking&Food', 'Cooking&Food'), ('Health&Wellness', 'Health&Wellness')], max_length=30, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
